# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Vote'),
        ),
    ]
