# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20160107_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='number',
        ),
    ]
